In [3]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
ones = np.ones(10, dtype=np.uint8)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [42]:
ones[1]

np.uint8(1)

In [6]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [30]:
np.repeat(5, 10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [31]:
np.repeat([0.0, 1.0], [2, 3])

array([0., 0., 1., 1., 1.])

In [32]:
np.repeat([1, 4], 5)

array([1, 1, 1, 1, 1, 4, 4, 4, 4, 4])

In [36]:
o = np.array([0, 11, 20, 13, 22])
o

array([ 0, 11, 20, 13, 22])

In [37]:
o[[4, 3, 1]]

array([22, 13, 11])

In [8]:
a = np.array([1, 2, 3, 4, 5])

In [9]:
a

array([1, 2, 3, 4, 5])

In [14]:
a[2]

np.int64(3)

In [15]:
int(a[0])

1

In [16]:
a[3] = 10

In [17]:
a

array([ 1,  2,  3, 10,  5])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [27]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [28]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [21]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
n[1]

array([4, 5, 6])

In [9]:
n[0][2] = 10

In [10]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [12]:
n[0, 2] = 11

In [117]:
n

array([[1, 3, 3],
       [4, 5, 6],
       [7, 7, 9]])

In [15]:
n[:, 2]

array([11,  6,  9])

In [116]:
n[:]

array([[1, 3, 3],
       [4, 5, 6],
       [7, 7, 9]])

In [119]:
n[:, 1] = [3, 5, 7]  

In [18]:
n

array([[ 1,  3, 11],
       [ 4,  5,  6],
       [ 7,  7,  9]])

In [40]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [46]:
print(100 * np.random.rand(4))

[62.11338328 52.91420943 13.45799453 51.35781213]


In [45]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [49]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[63, 79],
       [49, 39],
       [46,  8],
       [50, 15],
       [ 8, 17]])

In [44]:
np.random.seed(5)
np.random.rand(5, 2).round(2)

array([[0.22, 0.87],
       [0.21, 0.92],
       [0.49, 0.61],
       [0.77, 0.52],
       [0.3 , 0.19]])

In [5]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [4]:
a * 2

array([0, 2, 4, 6, 8])

In [6]:
b = ((a * 2) + 10) ** 2
b

array([100, 144, 196, 256, 324])

In [6]:
a + b

array([100, 145, 198, 259, 328])

In [7]:
a >= 2

array([False, False,  True,  True,  True])

In [8]:
a > b

array([False, False, False, False, False])

In [65]:
a[a >= 2]

array([2, 3, 4])

In [7]:
[a > b/100]

[array([False, False,  True,  True,  True])]

In [8]:
a[a > b/100]

array([2, 3, 4])

In [9]:
a

array([0, 1, 2, 3, 4])

In [12]:
int(a.min())

0

In [13]:
a.max()

np.int64(4)

In [14]:
a.sum()

np.int64(10)

In [17]:
float(a.mean())

2.0

In [18]:
a.std() #standard deviation -- .var() -> variance

np.float64(1.4142135623730951)

In [22]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
n.sum()

np.int64(45)

In [45]:
n.max(axis=1)  #largest number in each row

array([3, 6, 9])

In [46]:
n.max(axis=0) #largest number in each column

array([7, 8, 9])

In [47]:
n.sum(axis=1) #sum of elements in each row. axis=0 to get sum in each column.

array([ 6, 15, 24])

In [65]:
np.random.seed(6)
y = np.random.rand(4).round(2)
np.sort(y)

array([0.04, 0.33, 0.82, 0.89])

In [75]:
np.random.seed(6)
y = np.random.rand(4).round(2)
y.sort()
y

array([0.04, 0.33, 0.82, 0.89])

In [57]:
np.random.seed(4)
z = np.random.rand(10, 2).round(3)
np.sort(z)

array([[0.547, 0.967],
       [0.715, 0.973],
       [0.216, 0.698],
       [0.006, 0.976],
       [0.253, 0.435],
       [0.198, 0.779],
       [0.863, 0.983],
       [0.164, 0.597],
       [0.009, 0.387],
       [0.044, 0.957]])

In [58]:
z

array([[0.967, 0.547],
       [0.973, 0.715],
       [0.698, 0.216],
       [0.976, 0.006],
       [0.253, 0.435],
       [0.779, 0.198],
       [0.863, 0.983],
       [0.164, 0.597],
       [0.009, 0.387],
       [0.044, 0.957]])

In [79]:
y.shape

(4,)

In [80]:
z.shape

(10, 2)

In [83]:
x = np.random.randint(low=5, high = 20, size=12)
x

array([18, 15, 14, 11,  7, 16, 10, 10,  6,  9, 10, 19])

In [86]:
xreshape = x.reshape(3, 4)

In [87]:
xreshape

array([[18, 15, 14, 11],
       [ 7, 16, 10, 10],
       [ 6,  9, 10, 19]])

In [88]:
a = np.arange(3)
a

array([0, 1, 2])

In [89]:
b = np.arange(6).reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [91]:
np.concatenate([a, a])

array([0, 1, 2, 0, 1, 2])

In [92]:
np.concatenate([b, b])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [93]:
np.hstack([a, a])

array([0, 1, 2, 0, 1, 2])

In [94]:
np.vstack([a, a])

array([[0, 1, 2],
       [0, 1, 2]])

In [95]:
np.hstack([b, b])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [97]:
np.column_stack([a, b])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [98]:
np.column_stack([a, a])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [104]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [105]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
mat[2: 4]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [112]:
mat[:, 2]

array([ 2,  5,  8, 11, 14])

In [113]:
mat[1:3, :2]  #[row_slicing, column_slicing]

array([[3, 4],
       [6, 7]])

In [114]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])