In [1]:
import numpy as np

In [6]:
def vector_vector_mul(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [19]:
u = np.array([12, 8, 7])

In [20]:
v = np.array([10, 4, 2])

In [21]:
vector_vector_mul(u, v)

np.float64(166.0)

In [10]:
u.dot(v)

np.int64(166)

In [14]:
u.shape[0]

3

In [34]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_mul(U[i], v)

    return result

In [28]:
U = np.arange(12).reshape(3, 4)
U

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
v = np.arange(4)
v

array([0, 1, 2, 3])

In [35]:
matrix_vector_multiplication(U, v)

array([14., 38., 62.])

In [17]:
U.dot(v)

array([14, 38, 62])

In [3]:
V = np.arange(12).reshape(4, 3)
V = V+1
V

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
U.dot(V)

array([[ 48,  54,  60],
       [136, 158, 180],
       [224, 262, 300]])

In [36]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = uvi

    return result

In [37]:
matrix_matrix_multiplication(U, V)

array([[ 48.,  54.,  60.],
       [136., 158., 180.],
       [224., 262., 300.]])

In [6]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
V

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
V.dot(I)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [8]:
vsqr = V[[0, 1, 2]]
vsqr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.linalg.det(vsqr)  #to calculate determinant. For there to be an inverse, the det must not be 0.

np.float64(0.0)

In [19]:
vsqr[1, 1] = 0.5
vsqr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [20]:
np.linalg.det(vsqr) 

np.float64(59.999999999999986)

In [21]:
vs_inv = np.linalg.inv(vsqr)
vs_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [23]:
vs_inv.dot(vsqr).round(2) #should give an identity matrix

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
vsqr.dot(vs_inv).round(1)

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
np.allclose(vs_inv.dot(vsqr), np.eye(3))

True